esphome:
    name: frontdoorlight
    platform: ESP8266
    board: esp01_1m

<<: !include secrets.yaml
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

<<: !include ota.yaml

switch:
    - platform: gpio
      name: "Front door light"
      pin: 2