version: '3'

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:amd64
    restart: unless-stopped
    #user: root
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pie-hole:
    container_name: pie-hole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "41222:80/tcp"
      - "42223:443/tcp"
    environment:
      ServerIP: 10.0.0.3
      DNS1: '10.0.0.2#5054'
      DNS2: ''
      IPv6: 'false'
      DNSMASQ_LISTENING: all
      VIRTUAL_HOST: piehole.ronneylira.com
      TZ: ${TZ}
      WEBPASSWORD : ${WEBPASSWORD} # WEBPASSWORD: 'set a secure password here or it will be random'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
      # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      #- './etc-letsencrypt/live/piehole.ronneylira.com:/etc/certs/'
      #- './external.conf:/etc/lighttpd/external.conf'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    env_file: .env
    volumes:
      - $ROOT/dnsrobocert.yml:/etc/letsencrypt/dnsrobocert.yml
      - ./etc-letsencrypt:/etc/letsencrypt
      - ./config.yml:/etc/dnsrobocert/config.yml:ro
    environment:
      - VERSION=latest
    restart: always  

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      # Local path where your home assistant config will be stored
      - ./etc-home-assistant:/config
      - ./etc/localtime:/etc/localtime:ro
    environment:
      TZ : ${TZ}
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
#    user: "${LOCAL_USER}:${LOCAL_USER}"
  # nginx:
  #   image: nginx:1.15-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #     - ./init-letsencrypt.sh:/tmp/init-letsencrypt.sh
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29

volumes:
  pihole_etc:
  pihole_dnsmasq:
  le_certs:
  pihole_certs: